name: build

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build_STM32F407IGHx:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Add library target/link library
        run: |
          sed -i '67 a add_subdirectory(${{github.workspace}})' ${{github.workspace}}/stm32cube_template/stm32f407ighx/CMakeLists.txt
          sed -i '68 a link_libraries(irobotEC)' ${{github.workspace}}/stm32cube_template/stm32f407ighx/CMakeLists.txt

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=arm-none-eabi-gcc -DCMAKE_CXX_COMPILER:FILEPATH=arm-none-eabi-g++ -S${{github.workspace}}/stm32cube_template/stm32f407ighx -B${{github.workspace}}/stm32cube_template/stm32f407ighx/build -G "Unix Makefiles"

      - name: Build
        run: cmake --build ${{github.workspace}}/stm32cube_template/stm32f407ighx/build --target all

  build_STM32H723VGTx:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Add library target/link library
        run: |
          sed -i '67 a add_subdirectory(${{github.workspace}})' ${{github.workspace}}/stm32cube_template/stm32h723vgtx/CMakeLists.txt
          sed -i '68 a link_libraries(irobotEC)' ${{github.workspace}}/stm32cube_template/stm32h723vgtx/CMakeLists.txt

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=arm-none-eabi-gcc -DCMAKE_CXX_COMPILER:FILEPATH=arm-none-eabi-g++ -S${{github.workspace}}/stm32cube_template/stm32h723vgtx -B${{github.workspace}}/stm32cube_template/stm32h723vgtx/build -G "Unix Makefiles"

      - name: Build
        run: cmake --build ${{github.workspace}}/stm32cube_template/stm32h723vgtx/build --target all