
name: CI Style Lint

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: './framework'
          exclude: '**/mahony/*.*'
          extensions: 'h,cpp,cc,hpp,c'
          clangFormatVersion: 17
          style: google

