name: docs

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.ACC_TOKEN }}
          doxyfile-path: ./Doxyfile
          working-directory: .
          html-output-folder: doc/html
          branch: gh-pages